// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbuWeb.Data;

#nullable disable

namespace Nbuweb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240521152532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NbuWeb.Models.BankProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("CanReinvest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FixedTerm")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FlexTerm")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InterestPaymentInterval")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("MaxTermLength")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.ToTable("BankProducts");
                });

            modelBuilder.Entity("NbuWeb.Models.DepositDetail", b =>
                {
                    b.Property<int>("DepositDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepositDetailId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TermLength")
                        .HasColumnType("int");

                    b.HasKey("DepositDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("DepositDetails");
                });

            modelBuilder.Entity("NbuWeb.Models.InterestDetail", b =>
                {
                    b.Property<int>("InterestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InterestDetailId"));

                    b.Property<int>("BankProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("BgnInterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EarlyWithdrawalPenaltyRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EurInterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GovernmentTaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TermLengthInMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("UsdInterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("InterestDetailId");

                    b.HasIndex("BankProductId");

                    b.ToTable("InterestDetails");
                });

            modelBuilder.Entity("NbuWeb.Models.DepositDetail", b =>
                {
                    b.HasOne("NbuWeb.Models.BankProduct", "BankProduct")
                        .WithMany("DepositDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankProduct");
                });

            modelBuilder.Entity("NbuWeb.Models.InterestDetail", b =>
                {
                    b.HasOne("NbuWeb.Models.BankProduct", "BankProduct")
                        .WithMany("InterestDetails")
                        .HasForeignKey("BankProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankProduct");
                });

            modelBuilder.Entity("NbuWeb.Models.BankProduct", b =>
                {
                    b.Navigation("DepositDetails");

                    b.Navigation("InterestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
